// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvA47xt2hTj2HDMASWkX1u0FFqYE2CJ1A',
    appId: '1:125999704398:web:2fd8666802ab7d4c63d61f',
    messagingSenderId: '125999704398',
    projectId: 'chatapp-fe825',
    authDomain: 'chatapp-fe825.firebaseapp.com',
    storageBucket: 'chatapp-fe825.appspot.com',
    measurementId: 'G-8XDBCV72E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0oienGs9ylPK-NBECRvOkyxHlapsWBFY',
    appId: '1:125999704398:android:b658ba46106c32f563d61f',
    messagingSenderId: '125999704398',
    projectId: 'chatapp-fe825',
    storageBucket: 'chatapp-fe825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoKXgE8jdAFxzUuVj1mOnCwR2FcWfpr_k',
    appId: '1:125999704398:ios:d5dfa2de6c7e22b863d61f',
    messagingSenderId: '125999704398',
    projectId: 'chatapp-fe825',
    storageBucket: 'chatapp-fe825.appspot.com',
    androidClientId: '125999704398-7pp5292gcqb3rn45tgr8539mu2suatl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
